package com.helianhealth.family.he.admin.model.wgtj;

import lombok.Data;

@Data
public class DanganInfo {
    private String xingbie;
    private String isXgZdrq;
    private String rid;
    private String hunyinZk;
    private String photoFileFid;
    private String danganGbh;
    private String shenfenZh;
    private String benrenLxdh;
    private String danganCdrs;
    private String guanliDw;
    private String lianxiGx;
    private String xianjuD;
    private String isPkrk;
    private String yiyuanFidCh;
    private String danganBz;
    private String chushengRq;
    private String changzhuLx;
    private String lianxiRxm2;
    private String isJhb;
    private String xuexing;
    private String minzuCh;
    private String jiankangDabh;
    private String nianlingYear;
    private String xingming;
    private String isJhbCh;
    private String areaCode;
    private String jiwangSjb;
    private Boolean haveRole;
    private String createUserFid;
    private String minzu;
    private String zerenYsFid;
    private String jiandangDw;
    private String updateUserFid;
    private String xiangzhenBmFid;
    private String gridCode;
    private String zhengjianLx;
    private String hunyinZkCh;
    private String canjiQk;
    private String hujiD;
    private String canjiQkCh;
    private String isDagk;
    private String danganHbh;
    private String isYfjz;
    private String danganLx;
    private Long serialVersionUID;
    private String isYcfCh;
    private String isYfjzCh;
    private String yiyuanFid;
    private String zuihouSfrq;
    private String yiliaoFyzffsCh;
    private String xuexingCh;
    private String jiwangSjbCh;
    private String jiandangRq;
    private String updateTime;
    private String yiliaoFyzffs;
    private String lianxiRdh;
    private String danganLxCh;
    private String qitaSm;
    private String xingbieCh;
    private String isYcf;
    private String jiandangRenFid;
    private String lianxiGx2;
    private String cunweiBm;
    private String createTime;
    private String icCard;
    private String changzhuLxCh;
    private String isXgZdrqCh;
    private String lianxiRdh2;
    private String lianxiRxm;
}
