# æ°æ®åºéç½®ï¼SQLiteï¼é¶é¨ç½²ï¼åæä»¶ sync.db ä¸é¡¹ç®åç®å½ï¼
jdbc.driver=org.sqlite.JDBC
jdbc.url=jdbc:sqlite:./sync.db
jdbc.username=
jdbc.password=

# ç½å³æ¥å£éç½®
gateway.fid=HL07731
gateway.isPrint=2
gateway.userId=1655
gateway.token=d4030aabb095fb0eb76599a81d68fa041655
gateway.stationId=HL07731

sync.startMonth=2020-01
sync.endMonth=2019-01
